name: AutoBuild
on:
  push:
    branches:
      - main
jobs:
  ubuntu-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo sources
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build
      - name: Hash output jar
        run: |
          md5sum build/libs/* > build/libs/artifacts.md5
      - name: Store Out Jar
        uses: actions/upload-artifact@v2
        with:
          path: build/libs/*
