name: AutoBuild
on:
  push:
    branches:
      - main
jobs:
  ubuntu-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build
      - name: Store Test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report (Ubuntu)
          path: build/reports/tests/test
      - name: Store Out Jar
        uses: actions/upload-artifact@v2
        with:
          name: Jar Artifact (Ubuntu)
          path: build/libs/GitActionsTester-1.0-SNAPSHOT.jar
  macos-build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build
      - name: Store Test report
        uses: actions/upload-artifact@v2
        with:
          name: Test report (MacOS)
          path: build/reports/tests/test
      - name: Store Out Jar
        uses: actions/upload-artifact@v2
        with:
          name: Jar Artifact (MacOS)
          path: build/libs/GitActionsTester-1.0-SNAPSHOT.jar
